### ISSUE TITLE
README example code is outdated

### ISSUE THREAD

**Issue by ParaPenguin** [Ullink/simple-slack-api#41]
Title speaks all, really. Regarding the updating and deletion of the message sent, I had to rummage around the source to find a solution, which was actually casting the getReply() from the event to the correct class. Seems a little sketchy if you ask me, but oh well.

**Comment by bcorne** [comment]
ok I take it :)

**Comment by NomNuggetNom** [comment]
What did you cast it to? Updating is not working for me.

**Comment by nishtahir** [comment]
I can confirm this.  After investigating a little bit it seems that after sending a message, resulting object does not have a `reply_to` property causing the SlackJSONReplyParser to return a `GenericSlackReplyImpl` instead of a `SlackMessageReplyImpl`. This causes a masked class cast exception which is not visible in the log output. 

The only work around I could come up with is to cast the `getReply` from handle and manually parse the JSON

```
((GenericSlackReply) handle.getReply()).getPlainAnswer()
```

I'd attempt to fix it, but i'm still trying to figure out whether or not slack message replies always include a `reply_to` property or not.

**Comment by ParaPenguin** [comment]
I fixed one error regarding this a while ago, however there are many occurrences of this and it can become somewhat confusing to fix them all. It feels like the visible API methods were changed after the backend was written. It would take a lot of work to convert it all

**Comment by nishtahir** [comment]
Well we need to start somewhere...

On the other hand I guess a simple way of solving the sample code problem would be to add the sample code in a sample subproject. That way the build would fail if the sample code isn't up to date.

**Comment by bcorne** [comment]
I just started the samples :) some more will come soon

**Comment by bcorne** [comment]
Just to add some details on this issue, reply_to in only used for message sent using the RTM API ( so using sendMessageOverWebSocket method).

**Comment by bcorne** [comment]
I've investigated further, so indeed the `reply_to` check was the culprit, I've replaced it by a `ts` presence check in the JSON reply

**Comment by bcorne** [comment]
fixed with d8d6a1f commit
